name: love_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.3
  audioplayers: ^6.5.0
  vibration: ^3.2.0
  http: ^1.6.0
  shared_preferences: ^2.5.5
  just_audio: ^0.10.6
  audio_service: ^0.18.19
  path_provider: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/nursaule.png
    - assets/sounds/
    - assets/music/
    - assets/covers/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/nursaule.png"

  adaptive_icon_background: "#F8C3D8"
  adaptive_icon_foreground: "assets/nursaule.png"

  web:
    generate: true
    image_path: "assets/web_icon.png"
    background_color: "#02040D"
    theme_color: "#02040D"